namespace Klyte.DynamicTextProps.UI.Images
{
    public enum LineIconSpriteNames
    {
        MapIcon,
        OvalIcon,
        RoundedHexagonIcon,
        RoundedPentagonIcon,
        RoundedTriangleIcon,
        OctagonIcon,
        HeptagonIcon,
        S10StarIcon,
        S09StarIcon,
        S07StarIcon,
        S06StarIcon,
        S05StarIcon,
        S04StarIcon,
        S03StarIcon,
        CameraIcon,
        MountainIcon,
        ConeIcon,
        TriangleIcon,
        CrossIcon,
        DepotIcon,
        ParachuteIcon,
        HexagonIcon,
        SquareIcon,
        PentagonIcon,
        TrapezeIcon,
        DiamondIcon,
        S08StarIcon,
        CircleIcon,
        RoundedSquareIcon
    };
}
